language: node_js
node_js:
  - lts/*
script:
  - npm run docs:build
deploy:
  provider: pages
  skip_cleanup: true # otherwise everything we have done will be deleted again
  local_dir: docs/.vuepress/dist
  github_token: $GITHUB_TOKEN # a token generated on github allowing travis to push code on you repository
  keep_history: true
  on:
    branch: master
